Fix for overwriting existing resources
Existing resources were getting a double '.tres' exention causing a:
ERROR: Another resource is loaded from path
This fix addresses that.